// Base de datos de hechos curiosos
const facts = [
    "The name Wendy was made up for the book 'Peter Pan.'",
    "Barbie's full name is Barbara Millicent Roberts.",
    "Every time you lick a stamp, you consume 1/10 of a calorie.",
    "The average person falls asleep in seven minutes.",
    "Studies show that if a cat falls off the seventh floor of a building it has about thirty percent less chance of surviving than a cat that falls off the twentieth floor. It supposedly takes about eight floors for the cat to realize what is occurring, relax and correct itself.",
    "Your stomach has to produce a new layer of mucus every 2 weeks otherwise it will digest itself.",
    "The citrus soda 7-UP was created in 1929; '7' was selected after the original 7-ounce containers and 'UP' for the direction of the bubbles.",
    "101 Dalmatians, Peter Pan, Lady and the Tramp, and Mulan are the only Disney cartoons where both parents are present and don't die throughout the movie.",
    "A pig's orgasm lasts for 30 minutes.",
    "'Stewardesses' is the longest word that is typed with only the left hand.",
    "To escape the grip of a crocodile's jaws, push your thumbs into its eyeballs - it will let you go instantly.",
    "Reindeer like to eat bananas.",
    "No word in the English language rhymes with month, orange, silver and purple.",
    "The word 'samba' means 'to rub navels together.'",
    "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
    "The electric chair was invented by a dentist.",
    "The very first bomb dropped by the Allies on Berlin during World War II Killed the only elephant in the Berlin Zoo.",
    "More people are killed annually by donkeys than airplane crashes.",
    "A 'jiffy' is a unit of time for 1/100th of a second.",
    "A whale's penis is called a dork.",
    "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
    "The average person spends 6 months of their life sitting at red lights.",
    "In 1912 a law passed in Nebraska where drivers in the country at night were required to stop every 150 yards, send up a skyrocket, wait eight minutes for the road to clear before proceeding cautiously, all the while blowing their horn and shooting off flares.",
    "More Monopoly money is printed in a year, than real money throughout the world.",
    "Caesar salad has nothing to do with any of the Caesars. It was first concocted in a bar in Tijuana, Mexico, in the 1920's.",
    "One quarter of the bones in your body are in your feet.",
    "Crocodiles and alligators are surprisingly fast on land. Although they are rapid, they are not agile. So, if being chased by one, run in a zigzag line to lose him or her.",
    "Seattle's Fremont Bridge rises up and down more than any drawbridge in the world.",
    "Right-handed people live, on average; nine years longer than left handed people.",
    "Ten percent of the Russian government's income comes from the sale of vodka.",
    "In the United States, a pound of potato chips costs two hundred times more than a pound of potatoes.",
    "A giraffe can go without water longer than a camel.",
    "Nearly 80% of all animals on earth have six legs.",
    "Ninety percent of all species that have become extinct have been birds.",
    "There is approximately one chicken for every human being in the world.",
    "Most collect calls are made on father's day.",
    "Each of us generates about 3.5 pounds of rubbish a day, most of it paper.",
    "Women manage the money and pay the bills in 75% of all Americans households.",
    "A rainbow can be seen only in the morning or late afternoon. It can occur only when the sun is 40 degrees or less above the horizon.",
    "It has NEVER rained in Calama, a town in the Atacama Desert of Chile.",
    "The plastic things on the end of shoelaces are called aglets.",
    "Daylight Saving Time is not observed in most of the state of Arizona and parts of Indiana.",
    "Ants closely resemble human manners: When they wake, they stretch & appear to yawn in a human manner before taking up the tasks of the day.",
    "Bees have 5 eyes. There are 3 small eyes on the top of a bee's head and 2 larger ones in front.",
    "Count the number of cricket chirps in a 15-second period, add 37 to the total, and your result will be very close to the actual outdoor Fahrenheit temperature.",
    "One-fourth of the world's population lives on less than $200 a year. Ninety million people survive on less than $75 a year.",
    "Butterflies taste with their hind feet.",
    "Only female mosquito's bite and most are attracted to the color blue twice as much as to any other color.",
    "If one places a tiny amount of liquor on a scorpion, it will instantly go mad and sting itself to death.",
    "It is illegal to hunt camels in the state of Arizona.",
    "In eighteenth-century English gambling dens, there was an employee whose only job was to swallow the dice if there was a police raid.",
    "There are no clocks in Las Vegas gambling casinos.",
    "The human tongue tastes bitter things with the taste buds toward the back. Salty and pungent flavors are tasted in the middle of the tongue, sweet flavors at the tip!",
    "The first product to have a bar code was Wrigley's gum.",
    "When you sneeze, air and particles travel through the nostrils at speeds over 100 mph. During this time, all bodily functions stop, including your heart.",
    "Annual growth of WWW traffic is 314,000%",
    "60% of all people using the Internet, use it for pornography.",
    "In 1778, fashionable women of Paris never went out in blustery weather without a lightning rod attached to their hats.",
    "Sex burns 360 calories per hour.",
    "A raisin dropped in a glass of fresh champagne will bounce up and down continually from the bottom of the glass to the top.",
    "Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it.",
    "The average lead pencil will draw a line 35 miles long or write approximately 50,000 English words.",
    "The pop you hear when you crack your knuckles is actually a bubble of gas burning.",
    "You burn more calories sleeping than you do watching TV.",
    "In a lifetime the average human produces enough quarts of spit to fill 2 swimming pools.",
    "Barbie's measurements, if she were life-size, would be 39-29-33.",
    "The human heart creates enough pressure to squirt blood 30ft.",
    "One third of all cancers are sun related.",
    "It has been estimated that humans use only 10% of their brain.",
    "1 in every 4 Americans has appeared someway or another on television.",
    "1 in 8 Americans has worked at a McDonalds restaurant.",
    "70% of all boats sold are used for fishing.",
    "Studies have shown that children laugh an average of 300 times/day and adults 17 times/day.",
    "A pregnant goldfish is called a twit.",
    "The shortest war in history was between Zanzibar and England in 1896. Zanzibar surrendered after 38 minutes.",
    "You were born with 300 bones, but by the time you are an adult you will only have 206.",
    "If you go blind in one eye you only lose about one fifth of your vision but all your sense of depth.",
    "Women blink nearly twice as much as men.",
    "The strongest muscle (relative to size) in the body is the tongue.",
    "A Boeing 747's wingspan is longer than the Wright brother's first flight.",
    "American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served in first-class.",
    "The first CD pressed in the US was Bruce Springsteen's 'Born in the USA'",
    "The thumbnail grows the slowest, the middle nail the fastest, nearly 4 times faster than toenails.",
    "The Human eyes never grow, but nose and ears never stop growing.",
    "The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had.",
    "Tom Sawyer was the first novel written on a typewriter.",
    "If Texas were a country, its GNP would be the fifth largest of any country in the world.",
    "There are 1 million ants for every human in the world.",
    "Since 1978, 37 people have died by Vending Machine's falling on them. 13 people are killed annually.",
    "The 'Golden Arches' of fast food chain McDonalds is more recognized worldwide than the religious cross of Christianity.",
    "Former basketball superstar Michael Jordan is the most recognized face in the world, more than the pope himself.",
    "The average talker sprays about 300 microscopic saliva droplets per minute, about 2.5 droplets per word.",
    "The Earth experiences 50,000 Earth quakes per year and is hit by Lightning 100 times a second.",
    "Every year 11,000 Americans injure themselves while trying out bizarre sexual positions.",
    "On average, Americans eat 18 acres of pizza everyday.",
    "During a severe windstorm or rainstorm the Empire State Building sways several feet to either side.",
    "In the last 3,500 years, there have been approximately 230 years of peace throughout the civilized world.",
    "The Black Death reduced the population of Europe by one third in the period from 1347 to 1351.",
    "The average person spends about two years on the phone in a lifetime.",
    "A full-loaded supertanker traveling at normal speed takes at least 20 minutes to stop.",
    "Coca-Cola was originally green.",
    "Men can read smaller print than women; women can hear better.",
    "Hong Kong holds the most Rolls Royce's per capita.",
    "Average number of people airborne over the US any given hour: 61,000.",
    "Intelligent people have more zinc and copper in their hair.",
    "Iceland consumes more Coca-Cola per capita than any other nation.",
    "The San Francisco Cable cars are the only mobile National Monuments.",
    "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
    "'I am.' is the shortest complete sentence in the English language.",
    "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
    "The longest recorded flight of a chicken is thirteen seconds.",
    "The name Jeep came from the abbreviation used in the army. G.P. for 'General Purpose' vehicle.",
    "The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.",
    "Honking of car horns for a couple that just got married is an old superstition to insure great sex.",
    "The Black Widow spider eats her mate during or after sex.",
    "When a Hawaiian woman wears a flower over her left ear, it means that she is not available.",
    "The only nation whose name begins with an 'A', but doesn't end in an 'A' is Afghanistan.",
    "Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.",
    "Cats have over one hundred vocal sounds, while dogs only have about ten.",
    "Blueberry Jelly Bellies were created especially for Ronald Reagan.",
    "The airplane Buddy Holly died in was the 'American Pie.' (Thus the name of the Don McLean song.)",
    "Each king in a deck of playing cards represents a great king from history. Spades - King David, Clubs - Alexander the Great, Hearts - Charlemagne, and Diamonds - Julius Caesar.",
    "Golf courses cover 4% of North America.",
    "The average person will accidentally eat just under a pound of insects every year.",
    "The Great Wall of China is the only man-made structure visible from space.",
    "A piece of paper can be folded no more then 9 times.",
    "The average North American will eat 35,000 cookies during their life span.",
    "Between 25% and 33% of the population sneeze when exposed to light.",
    "The most common name in world is Mohammed.",
    "Mount Olympus Mons on Mars is three times the size of Mount Everest.",
    "Most toilets flush in E flat.",
    "2,000 pounds of space dust and other space debris fall on the Earth every day.",
    "40,000 Americans are injured by toilets each year.",
    "It takes about 142.18 licks to reach the center of a Tootsie pop.",
    "It is illegal to eat oranges while bathing in California.",
    "The average American butt is 14.9 inches long.",
    "60% of electrocutions occur while talking on the telephone during a thunderstorm.",
    "3.6 cans of Spam are consumed each second.",
    "There's a systematic lull in conversation every 7 minutes.",
    "There are 1,575 steps from the ground floor to the top of the Empire State building.",
    "There are 293 ways to make change for a dollar.",
    "The world record for spitting a watermelon seed is 65 feet 4 inches.",
    "In the Philippine jungle, the yo-yo was first used as a weapon.",
    "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
    "Texas is the only state that is allowed to fly its state flag at the same height as the U.S. flag.",
    "The three most recognized Western names in China are Jesus Christ, Richard Nixon, & Elvis Presley.",
    "There is a town in Newfoundland, Canada called Dildo.",
    "All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.",
    "In space, astronauts are unable to cry, because there is no gravity and the tears won't flow.",
    "Chewing gum while peeling onions will keep you from crying.",
    "There are more plastic flamingos in the U.S that there are real ones.",
    "The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.",
    "Jupiter is bigger than all the other planets in our solar system combined.",
    "Hot water is heavier than cold.",
    "Lawn darts are illegal in Canada.",
    "Between 2 and 3 jockeys are killed each year in horse racing.",
    "The average woman consumes 6 lbs of lipstick in her lifetime.",
    "Conception occurs most in the month of December.",
    "CBS' '60 Minutes' is the only TV show without a theme song/music.",
    "Half of all Americans live within 50 miles of their birthplace.",
    "'Obsession' is the most popular boat name.",
    "On average, Americans' favorite smell is banana.",
    "Honey is the only food which does not spoil.",
    "3.9% of all women do not wear underwear.",
    "Babies are born without kneecaps. They don't appear until the child reaches 2-6 years of age.",
    "In 1980, a Las Vegas hospital suspended workers for betting on when patients would die.",
    "The only real person to ever to appear on a pez dispenser was Betsy Ross.",
    "Mike Nesmith's (the guitarist of The Monkeys) mom invented White Out.",
    "Only 6 people in the whole world have died from moshing.",
    "In a test performed by Canadian scientists, using various different styles of music, it was determined that chickens lay the most eggs when pop music was played.",
    "The storage capacity of human brain exceeds 4 Terabytes.",
    "In Vermont, the ratio of cows to people is 10:1",
    "Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.",
    "The average American looks at eight houses before buying one.",
    "In the average lifetime, a person will walk the equivalent of 5 times around the equator.",
    "Koala is Aboriginal for 'no drink'.",
    "Shakespeare spelled his OWN name several different ways.",
    "The first contraceptive was crocodile dung used by the ancient Egyptians.",
    "Arnold Schonberg suffered from triskaidecaphobia, the fear of the number 13. He died at 13 minutes from midnight on Friday the 13th.",
    "Mozart wrote the nursery rhyme 'twinkle, twinkle, little star' at the age of 5.",
    "Weatherman Willard Scott was the first original Ronald McDonald.",
    "Virginia Woolf wrote all her books standing.",
    "Einstein couldn't speak fluently until after his ninth birthday. His parents thought he was mentally retarded.",
    "Al Capone's business card said he was a used furniture dealer.",
    "Deborah Winger did the voice of E.T.",
    "Kelsey Grammar sings and plays the piano for the theme song of Fraiser.",
    "Thomas Edison, acclaimed inventor of the light bulb, was afraid of the dark.",
    "In England, the Speaker of the House is not allowed to speak.",
    "You can sail all the way around the world at latitude 60 degrees south.",
    "The earth weighs around 6,588,000,000,000,000,000,000,000,000 tons.",
    "Peanuts are one of the ingredients of dynamite.",
    "Porcupines can float in water.",
    "The average person's left hand does 56% of the typing.",
    "A shark is the only fish that can blink with both eyes.",
    "The longest one-syllable word in the English language is 'screeched.'",
    "All of the clocks in the movie 'Pulp Fiction' are stuck on 4:20, a national pot-smokers hour.",
    "'Dreamt' is the only English word that ends in the letters 'mt.'",
    "Almonds are a member of the peach family.",
    "Winston Churchill was born in a ladies' room during a dance.",
    "Maine is the only state whose name is just one syllable.",
    "There are only four words in the English language which end in 'dous': tremendous, horrendous, stupendous, and hazardous.",
    "Tigers not only have striped fur, they have striped skin!",
    "In most advertisements, including newspapers, the time displayed on a watch is 10:10.",
    "On the ground, a group of geese is a gaggle, in the sky it is a skein.",
    "When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state's third largest city.",
    "The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra's 'Its A Wonderful Life.'",
    "A dragonfly has a lifespan of 24 hours.",
    "A dime has 118 ridges around the edge.",
    "Mr. Rogers is an ordained minister.",
    "John Lennon's first girlfriend was named Thelma Pickles.",
    "There are 336 dimples on a regulation golf ball.",
    "A crocodile cannot stick its tongue out.",
    "A snail can sleep for three years.",
    "All polar bears are left-handed.",
    "China has more English speakers than the United States.",
    "Elephants are the only animals that can't jump.",
    "February 1865 is the only month in recorded history not to have a full moon.",
    "If you yelled for 8 years, 7 months and 6 days, you will have produced enough sound energy to heat one cup of coffee.",
    "In the last 4000 years, no new animals have been domesticated.",
    "Leonardo Da Vinci invented the scissors.",
    "The word 'set' has more definitions than any other word in the English language.",
    "Nutmeg is extremely poisonous if injected intravenously.",
    "On average, people fear spiders more than they do death.",
    "Shakespeare invented the word 'assassination' and 'bump'.",
    "Some lions mate over 50 times a day.",
    "Starfish haven't got brains.",
    "The ant always falls over on its right side when intoxicated.",
    "The name of all continents in the world end with the same letter that they start with.",
    "There are two credit cards for every person in the United States.",
    "You can't kill yourself by holding your breath.",
    "The average person spends 12 weeks a year 'looking for things'.",
    "The symbol on the 'pound' key (#) is called an octothorpe.",
    "The dot over the letter 'i' is called a tittle.",
    "Ingrown toenails are hereditary.",
    "'Underground' is the only word in the English language that begins and ends with the letters 'und'",
    "The longest word in the English language is: pneumonoultramicroscopicsilicovolcanoconiosis.",
    "An ostrich's eye is bigger than its brain.",
    "Alfred Hitchcock didn't have a belly button. It was eliminated when he was sewn up after surgery.",
    "Telly Savalas and Louis Armstrong died on their birthdays.",
    "Donald Duck's middle name is Fauntleroy.",
    "The muzzle of a lion is like a fingerprint - no two lions have the same pattern of whiskers.",
    "Steely Dan got their name from a sexual device depicted in the book 'The Naked Lunch'.",
    "A goldfish has a memory span of three seconds.",
    "Rubber bands last longer when refrigerated.",
    "The national anthem of Greece has 158 verses. No one in Greece has memorized all 158 verses.",
    "Two-thirds of the world's eggplant is grown in New Jersey.",
    "The giant squid has the largest eyes in the world.",
    "Giraffes have no vocal cords.",
    "The pupils of a goat's eyes are square.",
    "Van Gogh only sold one painting when he was alive.",
    "A standard slinky measures 87 feet when stretched out.",
    "If a rooster can't fully extend its neck, it can't crow.",
    "There were always 56 curls in Shirley Temple's hair.",
    "The eyes of a donkey are positioned so that it can see all four feet at all times.",
    "Rhode Island is the only state which the hammer throw is a legal high school sport.",
    "The average lifespan of an eyelash is five months.",
    "A spider has transparent blood.",
    "Prince Charles is an avid collecter of toilet seats.",
    "The most common street name in the U.S. is Second Street.",
    "Babies are most likely to be born on Tuesdays.",
    "In Miconesia, coins are 12 feet across.",
    "A horse can look forward with one eye and back with the other.",
    "Shakespeare is quoted 33,150 times in the Oxford English dictionary.",
    "The word Pennsylvania is misspelled on the Liberty Bell.",
    "NBA superstar Michael Jordan was originally cut from his high school basketball team.",
    "You spend 7 years of your life in the bathroom.",
    "Most dust particles in your house are made from dead skin.",
    "Venus is the only planet that rotates clockwise.",
    "Oak trees do not produce acorns until they are fifty years of age or older.",
    "The first owner of the Marlboro company died of lung cancer.",
    "All US Presidents have worn glasses; some just didn't like being seen wearing them in public.",
    "Mosquito repellents don't repel. They hide you. The spray blocks the mosquito's sensors so they don't know you're there.",
    "Walt Disney was afraid of mice.",
    "The king of hearts is the only king without a mustache.",
    "Pearls melt in vinegar.",
    "It takes 3,000 cows to supply the NFL with enough leather for a year's supply of footballs.",
    "Thirty-five percent of people who use personal ads for dating are already married.",
    "The 3 most valuable brand names on earth are Marlboro, Coca-Cola, and Budweiser (in that order).",
    "Humans are the only primates that don't have pigment in the palms of their hands.",
    "Months that begin on a Sunday will always have a 'Friday the 13th'.",
    "The fingerprints of koala bears are virtually indistinguishable from those of humans.",
    "The mask worn by Michael Myers in the original 'Halloween' was actually a Captain Kirk mask painted white.",
    "Only one person in two billion will live to be 116 or older.",
    "Dr. Jack Kevorkian first patient has Alzheimer's disease.",
    "It's possible to lead a cow upstairs but not downstairs.",
    "The very first song played on MTV was 'Video Killed The Radio Star' by the Buggles.",
    "38% of American men say they love their cars more than women",
    "100% of lottery winners do gain weight",
    "Bullet proof vests, fire escapes, windshield wipers, and laser printers were all invented by women",
    "A cat has 32 muscles in each ear.",
    "A duck's quack doesn't echo, and no one knows why.",
    "Cats urine glows under a black light.",
    "In every episode of Seinfeld there is a Superman somewhere.",
    "Pamela Anderson Lee is Canada's Centennial Baby, being the first baby born on the centennial anniversary of Canada's independence.",
    "Pinocchio is Italian for 'pine head.'",
    "When possums are playing 'possum', they are not 'playing.' They actually pass out from sheer terror.",
    "Most lipstick contains fish scales!",
    "Donald Duck comics were banned from Finland because he doesn't wear pants!",
    "There are more than 10 million bricks in the Empire State Building!",
    "Camels have three eyelids to protect themselves from blowing sand!",
    "Over 1000 birds a year die from smashing into windows!",
    "The state of Florida is bigger than England!",
    "Dolphins sleep with one eye open!",
    "In the White House, there are 13,092 knives, forks and spoons!",
    "Owls are one of the only birds who can see the color blue!",
    "Honeybees have a type of hair on their eyes!",
    "A jellyfish is 95 percent water!",
    "In Bangladesh, kids as young as 15 can be jailed for cheating on their finals!",
    "The katydid bug hears through holes in its hind legs!",
    "Q is the only letter in the alphabet that does not appear in the name of any of the United States!",
    "166,875,000,000 pieces of mail are delivered each year in the US",
    "Bats always turn left when exiting a cave",
    "The praying mantis is the only insect that can turn its head",
    "Daffy Duck's middle name is 'Dumas'",
    "In Disney's Fantasia, the Sorcerer's name is 'Yensid' (Disney backwards.)",
    "In The Empire Strikes Back there is a potato hidden in the asteroid field",
    "Walt Disney holds the world record for the most Academy Awards won by one person.",
    "Canada makes up 6.67 percent of the Earth's land area",
    "There are 1,792 steps in the Eiffel Tower",
    "There are 269 steps to the top of the Leaning Tower of Pisa",
    "Leonardo da Vinci could write with one hand while drawing with the other",
    "There are more chickens than people in the world.",
    "Los Angeles's full name is 'El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula'.",
    "It's impossible to sneeze with your eyes open.",
    "Table tennis balls have been known to travel off the paddle at speeds up to 160 km/hr.",
    "Pepsi originally contained pepsin, thus the name.",
    "The original story from 'Tales of 1001 Arabian Nights' begins, 'Aladdin was a little Chinese boy.'",
    "Hawaiian alphabet only has 12 letters: A, E, I, O, U, H, K, L, M, N, P, W",
    "Flamingos only can eat with their heads upside down.",
    "Lighter was invented ten years before the match was.",
    "It's physically impossible for a pig to look up at the sky.",
    "The first internet domain name to ever be registered is Symbolics.com on March 15th, 1985.",
    "Humans are born with 350 bones in their body, but when reaching adulthood, we only 260.",
    "This is impossible to tickle yourself.",
    "A typical pencil can draw a line that is 35 miles long.",
    "Astronauts get taller in space due to the lack of gravity.",
    "Mosquitos have contributed to more deaths than any animals on earth.",
    "An octopus has 3 hearts, 9 brains & blue blood.",
    "The hair on a polar bear is actually not white but clear. They appear white because it reflects light.",
    "A chameleon can move its eyes in two different directions at the same time.",
    "Buttermilk does not contain any butter and actually low in fat.",
    "A giraffe can go longer without water than a camel can.",
    "Australia has the biggest camel population in the world.",
    "Snails can sleep up to 3 years.",
    "Methane gases produced by cow products as much pollution as cars do.",
    "Most ice-cream contains pig skins (Gelatin).",
    "The Philippine island of Luzon contains a lake that contains an island that contains a lake that contains another island.",
    "Only one to two percent of the entire world population are natural redheads.",
    "Putting sugar on a wound or cut will greatly reduce pain and shorten healing process.",
    "Real diamonds do not show up in X-ray.",
    "Due to extreme pressure and weather conditions, it literally rains diamonds on Neptune and Uranus.",
    "Before the 17th century, carrots were actually purple. They didn't get their orange color until mutation occupied.",
    "A grammatical pedantry syndrome is a form of OCD in which suffers feel the need to correct every grammatical error that they see.",
    "Scorpions can hold their breath underwater for up to 6 days.",
    "In zero gravity, a candle's flame is round and blue.",
    "Only 8 percent of the world's money exists in physical form, the rest is in computers.",
    "Crows are able to recognize human faces and even hold grudges against ones that they don't like.",
    "Your cellphone carries up to ten times more bacteria than a toilet seat.",
    "Humans and bananas share about 50 percent of the same DNA.",
    "Humans have fewer chromosomes than a potato.",
    "Statistically, you are more likely to die on the way to buy a lottery ticket than you are to win the lottery itself.",
    "The word checkmate comes from the Arabic which means 'the king is dead.'",
    "Hot water turns to ice faster than cool water. This is known as the Mpemba effect.",
    "IV Is The Roman Numeral designation for 4 everywhere. However, on the clock face, 4 is displayed as 'IIII'.",
    "Japan has the most vending machines per capita, a staggering 1:23.",
    "Japanese police declare murders that they cannot solve as suicides, in order to save faces and keep crime rate artificially low.",
    "The smallest poisonous frogs only 10 millimeters (0.393701 inch) in length.",
    "Farting helps to reduce blood pressure and is good for your overall health.",
    "In 1994, the US Air Force did research on creating a gay bomb which is a non-lethal bomb containing very strong human sexual pheromones.",
    "There are around 1,584 people in the United States named 'Seven'.",
    "The classic heart shape that we all know was meant to be two hearts fused together.",
    "The water we drink is older than the sun. The sun is 4.6 billion years old.",
    "Michael Nicholson from Michigan has one bachelor's degree, two associate's degrees, 22 master's degrees, three specialist degrees and one doctoral degree.",
    "Practicing a kill in your head will make you better at it, but only if you're already good at it.",
    "If two identical twins have children with another pair of identical twins, then their children will genetically be full siblings.",
    "Killing a panda in China is a seriously crime. It is punishable by death.",
    "December 4th is the National Cookie Day!",
    "Beards can slow the aging process by stopping water from leaving the skin, keeping it moisturized.",
    "Most people dream in color, but those who grow up watching television in black and white are more likely to dream in black and white.",
    "Mixing your drinks with diet soda can get you drunk about 18% faster than regular soda.",
    "The number of H2O molecules in 10 drops of water is roughly equal to the total amount of stars in the universe.",
    "Octopuses have copper-based blood instead of iron-based blood, which is why their blood is blue rather than red.",
    "The hormones responsible for your growth are only produced when you sleep.",
    "You touch your face an average of once every three minutes.",
    "People who sleep less than six hours a night are 4.2 times more likely to catch a cold.",
    "Dogs can make about 100 different facial expressions.",
    "Iceland has no army as is often recognized as the most peaceful country in the world.",
    "Shigeru Miyamoto – maker of Super Mario Bros. and Donkey Kong – is not allowed to bike to work because his safety is too important to Nintendo.",
    "Every year, women lose approximately 1.73 billion bobby pins.",
    "Dolphins give each other 'names' – Specific sounds that they use to call friends and family.",
    "Chimpanzee babies like to play with dolls – They'll make dolls out of sticks and rocks for themselves.",
    "Squirrels plant thousands of trees every year, simply by forgetting where they put their acorns.",
    "Koalas can sleep for up to 20 hours a day.",
    "The average woman will spend one full year of her life trying to decide what to wear.",
    "The average woman owns eight times more makeup than she actually uses.",
    "Rainbows that appear at night are called 'moonbows.'",
    "100 million years ago, crocodiles had long legs and could gallop after their prey.",
    "The real Top Gun school give a $5 fine to any staff member that quotes the movie."
];

// Exportar hechos
window.factsData = facts;
